### ISSUE TITLE
Serialization issues when running list functions

### ISSUE THREAD

**Issue by lleger** [arlyon/async-stripe#118]
Hi! I'm trying to run some of the example code and running into a weird error. 

Here's the code: 

```rust
    let client = stripe::Client::new(stripe_api_key);

    let params = stripe::ListCharges::new();
    let charges = stripe::Charge::list(&client, params);
    println!("{:?}", charges);
```

Here's the error:

```
Err(JSONSerialize(Error("data did not match any variant of untagged enum Expandable", line: 13, column: 58)))
```

I'm using this version:
```
async-stripe = { version = "0.13.0-rc3", features = ["runtime-blocking"]}
```

I confirmed with the API key the Stripe request works using the CLI. I can also see the Rust queries in the Stripe dashboard succeed with a 200.

It's entirely possible I'm doing something wrong! I'm a Rust newbie.

**Comment by arlyon** [comment]
That is odd, can I ask what rust version you're on, and if you're able to capture the json response?

I'm in the process of re-enabling the doctests in this pr: https://github.com/arlyon/async-stripe/pull/119 but from initial tests, they pass (using [stripe-mock](https://github.com/stripe/stripe-mock)).

**Comment by lleger** [comment]
Rust version 1.56.1. 

I'm not actually sure how to capture the JSON response. The error occurs before it gets to the `println!` line — I think it's happening in the `list` function, so I never get a return from that function to check the response. Happy to do any more debugging, but this is literally the first Rust code I've written so I'm not super up on how to debug yet.

**Comment by arlyon** [comment]
That's no worries! I take it stripe doesn't save the responses in the console? What you could do instead is patch the crate. Rust lets you clone and refer to the crate locally, so you could try to print the request body before it is returned here: https://github.com/arlyon/async-stripe/blob/212a9ff88fe7b002f51b571c908114417e9ad573/src/client/tokio.rs#L285

Here's a resource in the rust docs that described the process of specifying a local path in `Cargo.toml`

If you'd like me to elaborate just let me know :)

**Comment by lleger** [comment]
Sadly Stripe does not save requests in the dashboard for successful GETs. I will try this though, thank you! Will report back.

**Comment by lleger** [comment]
Alright I was able to put that patch in place and from what's being printed I can confirm it's valid JSON.

**Comment by lleger** [comment]
The only thing I can tell is there are some fields coming back in the JSON that aren't present on the struct. Unsure if that is causing the issue or not.

**Comment by arlyon** [comment]
Yeah that'll do it, serde by default will error if the schema doesnt match the expected shape. Can you post a response (scrub any sensitive values if needed) and we'll figure out where to go. Do you know what stripe API version your account is on?

**Comment by lleger** [comment]
According to the Stripe dashboard the requests are using version 2020-08-27.

For charges list, it's missing these fields:
- `amount_updates`
- `destination`
- `dispute`
- `source`

For both charges list and balance transactions list (they only 2 I've tried), it's missing `object`. (Balance transactions isn't missing anything else.)

I can confirm that the output of `stripe charges list` and `stripe balance_transactions list` from the Stripe CLI matches the JSON response being printed out.

**Comment by lleger** [comment]
@arlyon Is there anything else I can do to help debug this? Is a patch as simple as updating the structs? If so I don't mind giving it a go.

**Comment by erichCompSci** [comment]
Hey @lleger why do you think it's missing those fields?  The API that the code is generated from doesn't seem to have those values so the code generation portion is working correctly and it would be strange for the API to be wrong.

**Comment by lleger** [comment]
@erichCompSci I compared the struct in the codebase to the JSON I received from Stripe's API.

**Comment by erichCompSci** [comment]
Okay, I just realized that you are using the latest up to date published version of the crate.  That one has some issues in it that have been fixed in mainline.  I think it would be best for you to use the master branch of this repository if you are hoping to do real work.  I'm building a backend with it right now and am actively supporting it, but I don't have time to go back and fix the previous versions.  The reason the stripe api doesn't match is because the version you are using is an older version with out of date code.

**Comment by lleger** [comment]
@erichCompSci Can you cut a new release to crate?

**Comment by erichCompSci** [comment]
I can not, because it's not my repo.  You'll have to wait until Arlyon releases the next one.  I should mention of course that this is an async library and you are using the runtime-blocking version of it.  There is already a well supported Stripe blocking API called stripe.  It is where arlyon originally forked his repo.  If all you need is something to connect to the Stripe backend, that may be better as it has lived longer and seems to have more people behind it.

**Comment by arlyon** [comment]
Hey @lleger, I have been a little busy wrapping stuff up before christmas but have free time starting tonight which I will use to sort out these issues, including merging @erichCompSci's PRs and releasing a new version.

**Comment by arlyon** [comment]
I have released a new version now, with the all the work @erichCompSci has included recently. I know it's been a while now (I managed to come down with COVID over christmas) but if the issue persists let me know!

**Comment by erichCompSci** [comment]
I think this is closed as well?
