### ISSUE TITLE
Expose Ephemeral Key Interface

### ISSUE THREAD

**Issue by erichCompSci** [arlyon/async-stripe#123]
Hey, I want to expose the ephemeral key interface by adding the appropriate few lines of code in generate.rs and resources.rs.  Since it's used in conjunction with payment_intents and setup_intents, my intention is to add it to the "core" functionality.

Is it okay, if I do this and get this pulled into mainline after?

**Comment by erichCompSci** [comment]
Hey Arlyon, I finished this.  Let me know if and when you're ready for the pull request.  Do you need me to look at some of the other issues?  I can't do everything, but I can take a look at some of them if you need some help.

**Comment by arlyon** [comment]
I appreciate your continued input. PRs welcome, I'm getting round to them (slowly!).
