### ISSUE TITLE
Fix new API Breakage

### ISSUE THREAD

**Issue by erichCompSci** [arlyon/async-stripe#126]
The latest API broke the code from compiling.  This was happening for two reasons.

1) The payment intent payment methods have introduced new data structures that do not match the previous standard.  This causes us to crash on an unwrap.  This was fixed by making the unwrap an unwrap_or_else to handle both the old style of unions and the new style.

2) After solving the first wrapping, we had a problem with duplicate names because our new unions just so happened to share the same name as other structs when they got through the union naming process.  To fix this, I added Union to the end of all "union" types automatically.  Since these types were already being renamed, it's clear that their actual type names are not important.  Thus, I feel confident that this is okay.

Take a look, let me know what you think, though its a lot.

**Comment by erichCompSci** [comment]
I combined all my pull requests into a single one, this gets fixed in there.

**Comment by arlyon** [comment]
Also closing this. Cheers!
