### ISSUE TITLE
CreatePaymentMethod has no Card Attribute

### ISSUE THREAD

**Issue by erichCompSci** [arlyon/async-stripe#132]
The CreatePaymentMethod doesn't have a card parameter.  Since this is probably the most common usage of this, that's probably pretty bad.  I'm looking into why this is happening as it is inconvenient for testing.

**Comment by erichCompSci** [comment]
Hilariously, I found the problem four minutes later...it's this:

`// TODO: Handle these unusual params
 "bank_account" | "card" | "destination" | "usage" => continue,
`
Looks like the avoidance is deliberate.

**Comment by erichCompSci** [comment]
Okay, I spent the day fixing this.  After a deeper dive into the code generation piece of this repo, I'm convinced that it's done in a less than ideal way.  I think the effort was to make this library Object Orientated focused, and that's not how the OpenAPI is set up.  The OpenAPI basically consists of two parts.  The "components" which are generally the responses to the "paths" which is the actual REST API.  As such, I think forcing the REST API to be a piece of some of the "components" causes a LOT of corner cases to be handled by hand in the generating code.

This is unfortunate and quite frank, fragile.  Plus, there is also a lot of code repeating (see the gen_inferred_params handling of required types), that should not be there.

Why am I mentioning this?  I'm actually using this library for some real work.  I need the code to work for years to come and I don't think it will.  So, I've started to make a dramatic change.  I started with the cards.  It adds a hybrid approach to this problem, with the intention of eventually moving to a different architecture.  One that actually supports the deletion posts in the OpenAPI and handles weird paths like the confirm and cancel API's of SetupIntent.

Let me know, if you are interested in joining me.  The goal is to reduce the hardcoding of specific types in the code generation piece of the code so that we aren't back here every other week fixing this back up.  I also want to reduce the code that needs to be hand written outside of the code generation even more than right now.

**Comment by arlyon** [comment]
I agree it's fragile as hell at the moment, and most of that is due to me patching up the old (and I agree, flawed) codegen. I have not made any significant changes to how the openapi spec is parsed / generated, only really focused on making the user-facing side nicer to use.

If you are able to tackle any of these oddities (even if that means throwing away the significant chunks of the old generation code) that would be amazing.

**Comment by arlyon** [comment]
You may also be interested in #85

**Comment by erichCompSci** [comment]
This is done and has been pulled into mainline.
