### ISSUE TITLE
CheckoutSession missing retrieve

### ISSUE THREAD

**Issue by SpaceEraser** [arlyon/async-stripe#211]
I'd want to retrieve an existing checkout session object, as in [https://stripe.com/docs/api/checkout/sessions/retrieve](https://stripe.com/docs/api/checkout/sessions/retrieve).

I'm new to the codebase, but I did some preliminary debugging, since this seems like a feature that should be implemented by the openapi code gen. The following seems to be excluding checkout sessions, since the checkout session URL has one more segment than expected:

https://github.com/arlyon/async-stripe/blob/40ed9a3798fc10dc35fd688272c6becc5f51a778/openapi/src/codegen.rs?plain=1#L1406

I patched it as follows, but the issue is really only observed with checkout sessions, so maybe it's not the best fix:

```Rust
} else if (segments.len() == 2 || (segments.len() == 3 && segments[1] == "sessions")) && !methods.contains_key(&MethodTypes::Retrieve) {
```

**Comment by arlyon** [comment]
Hi! Sorry for the late reply, I must have misunderstood the report earlier. This issue actually got reported again in #213 and prompted work on figuring out how to solve this. The solution I suggested in the other issue is to (if you'd like) write an extension object to add the method manually while we sort out #215. This may take some time so in the mean time I am for patching missing APIs manually in a non breaking feature release.

**Comment by arlyon** [comment]
This particular issue was solved with an manual ext service in PR https://github.com/arlyon/async-stripe/pull/244 so I am closing.
