### ISSUE TITLE
Incompatible features in 0.15.0

### ISSUE THREAD

**Issue by mzeitlin11** [arlyon/async-stripe#238]
Hi, thanks for this awesome package!

After updating to `0.15.0`, a set of features that built fine in `0.14.1` now doesn't compile. A minimal `Cargo.toml` which compiles for `0.14` but not `0.15.0`:
```
[dependencies]
async-stripe = {version = "0.15.0", default-features = false, features = ["runtime-tokio-hyper", "webhook-events", "checkout"]}
```

The compilation error:
```
error[E0412]: cannot find type `AccountCapabilities` in this scope
   --> /Users/matthewzeitlin/.cargo/registry/src/github.com-1ecc6299db9ec823/async-stripe-0.15.0/src/resources/webhook_events.rs:444:25
    |
444 |     AccountCapabilities(AccountCapabilities),
    |                         ^^^^^^^^^^^^^^^^^^^ not found in this scope
    |
help: there is an enum variant `crate::EventObject::AccountCapabilities`; try using the variant's enum
    |
444 |     AccountCapabilities(crate::EventObject),
    |                         ~~~~~~~~~~~~~~~~~~
```

Adding the feature `connect` fixes this compilation error - is this an intended change?

**Comment by mzeitlin11** [comment]
Sorry for the noise, looks like a duplicate of #137

**Comment by arlyon** [comment]
We need to probably come up with some heuristics on how 'sound' the features are. Definitely open to PRs to scan the source and figure out and implicit feature dependencies. Could you do me a favour and post this under a comment on #137 so that we don't lose this? TY
