### ISSUE TITLE
Search customer API

### ISSUE THREAD

**Issue by phungleson** [arlyon/async-stripe#260]
Hey peeps,

I am looking at stripe API, and it looks like they have a way to search for customers.

https://stripe.com/docs/api/customers/search

I couldn't find anything similar to that API in `async-stripe` I wonder if `async-stripe` has a way add that API into the library?

Cheers,

**Comment by arlyon** [comment]
Currently no, we only support list, which only allows filtering on a single email address.

**Comment by arlyon** [comment]
I am closing in favour of the tracking issue.
