### ISSUE TITLE
Cancel SetupIntent

### ISSUE THREAD

**Issue by ViktorWb** [arlyon/async-stripe#266]
Hi!

Is it possible to [cancel](https://stripe.com/docs/api/setup_intents/cancel) a SetupIntent? I see cancel in [PaymentIntent](https://github.com/arlyon/async-stripe/blob/master/src/resources/payment_intent_ext.rs#L34), but not for SetupIntent.

**Comment by arlyon** [comment]
Cancelling setupintent is not handled by the codegen so the `ext` is hand written. If you'd like to contribute one, it is more that appreciated!
