### ISSUE TITLE
Customer balance transaction API

### ISSUE THREAD

**Issue by ViktorWb** [arlyon/async-stripe#271]
Hi!
Is it possible to use the [customer balance transaction](https://stripe.com/docs/api/customer_balance_transactions) API?

I would like to contribute to it, but I am unsure because I haven't worked much with openapi/codegen. There seems to be some structs [generated](https://github.com/arlyon/async-stripe/blob/master/src/resources/generated/customer_balance_transaction.rs), but they are not exported and there are no methods.

Thanks!

**Comment by arlyon** [comment]
Hi!

It looks like we _do_ generate types for `CustomerBalanceTransaction` but the codegen does not currently generate any api associations. This is a known shortcoming and I'd like to rework the codegen but until then you can write a `customer_balance_transaction_ext.rs` file with the functions you'd expect and I will make sure you review it :)

**Comment by ViktorWb** [comment]
Allright, thank you! I will see what I can do.

**Comment by arlyon** [comment]
Closing in favour of the tracking issue.
