### ISSUE TITLE
Very slow compile time

### ISSUE THREAD

**Issue by petersn** [arlyon/async-stripe#275]
Hello,

`async-stripe` seems to have very slow compile times, of around 50 seconds for debug, and around two minutes for release. This is excluding the time to build its dependencies, just the time for `async-stripe` itself.

(Evaluated on my Ryzen 9 5950X with 128 GB of RAM, and a fast SSD, with rustc 1.65.0-nightly (878aef79d 2022-08-20).)

To reproduce, simply run:
```
cargo new --bin compile-time-test
cd compile-time-test
echo 'async-stripe = { version = "0.15.0", features = [ "runtime-tokio-hyper-rustls" ] }' >> Cargo.toml
time cargo build --release
```

I would have assumed this library should be able to build in a second or so excluding its dependencies. Am I doing something wrong here that I don't realize?

Thanks,

-Peter

**Comment by petersn** [comment]
Apologies, I think I didn't quite realize the general vibe of this library without looking more closely. I see now that it uses code gen off of an automated spec, and as a result has 60k lines of code (and there are features to disable bits one doesn't want). I assume reducing the compile time with this general design would be difficult, so presumably this issue should be closed as wont-fix.

I honestly assumed I was just doing something wrong, because two minute compile times seemed wrong to me.

**Comment by arlyon** [comment]
Yes, they're not ideal. I have been working on a few things that may help with this:

- remove feature flags in favour of a trait + GAT-based client
- split the api into subscrates (#196) to parallelize (and reduce the likelihood of recompilation) which will solve issues such as #137

I have also considered other more lightweight serialization libs but there has been no experimentation with that yet. The GAT work has been going slowly as a) it will take a few iterations to get a 'good' api and b) I have no strong motivation to release it before GATs are stabilized :).

I am open to PRs that:

- demonstrate improvement in code size / compile time (ex by replacing serde)
- split up the api into more granular groups

I am going to close this issue in favour of the more general discussion in #77 :)

Thanks for using the library!
