### ISSUE TITLE
Why is there no Balance::retrieve method?

### ISSUE THREAD

**Issue by kvzn** [arlyon/async-stripe#280]
There is `retrieve` api in the doc but not implemented, how can we add it, thank you boss!

[`balance retrieve`](https://stripe.com/docs/api/balance/balance_retrieve)

**Comment by arlyon** [comment]
There are a number of methods that are not automatically picked up by the codegen. You can either write an `ext` yourself following the pattern of the existing `_ext` files, or adjust the codegen to see why it is being ignored :)

**Comment by arlyon** [comment]
Closing in favour of #32 which tracks all requests of this type :)

Thanks for using the library.
