### ISSUE TITLE
Compilation fails with the following errors

### ISSUE THREAD

**Issue by pratik-mahamuni** [arlyon/async-stripe#281]
When inputting the following (from the main Readme) in the Cargo.toml, compilation fails with the error provided in the picture.
```
async-stripe = { version = "0.15.0", default-features = false, features = ["runtime-async-std-surf", "billing"] }
```
![image](https://user-images.githubusercontent.com/64231439/196701619-8fd2080f-c952-4cb3-8de6-5a582fb3cf5d.png)

Version `rustc = 1.62`

**Comment by arlyon** [comment]
Hello

I believe this may be related to https://github.com/arlyon/async-stripe/issues/137

I have an in-progress PR to resolve this by removing the feature flags altogether however it is blocked on GATs which are being stabilized in 1.65. I was close this and refer you to that issue. Any research into which combinations do and don't work would be much appreciated.

Alex
