### ISSUE TITLE
Rework examples structure

### ISSUE THREAD

**Issue by mzeitlin11** [arlyon/async-stripe#287]
Recently saw https://github.com/tokio-rs/axum/tree/main/examples as a cool way of doing examples. Main differences
- Examples are in `examples`, which is its own `workspace`
- There is no usage of `[[examples]]` in the root `Cargo.toml`
- Each example is its own workspace member with its own `Cargo.toml`

The advantages of this are:
- `dev-dependencies` only used in `examples` don't need to be in the root `Cargo.toml`. So in our specific case we could remove `actix-web`, `axum`, `rocket` (after #284). This should reduce CI conflicts due to changing versions, and now when just hacking on the main crate, `cargo` `check, clippy, test` no longer take the extra time of compiling `actix-web, axum, rocket`.
- Since the examples are isolated, dependency / feature-management is simpler for users (we can just specify the minimal isolated `Cargo.toml`, so a user can just copy that. This should also make learning about the large feature list easier since there are example feature settings.
- For those examples, we (I think) don't need to worry about MSRV since for example using an `actix-web` dep that only works for `>=1.62` is fine - it doesn't affect the crate MSRV so won't cause the same MSRV issues we've seen in CI.
- Right now running examples is tricky because you need to run (for example) `cargo check --examples --features ...` and the only examples that run will be the ones with matching `required-features`. With the workspace setup, each crate sets its own required features, so just need to run `cargo check` in the `examples` workspace as a way to verify in CI that all examples compile.
- This should be easier to maintain when `async-stripe` is split into multiple crates since the examples can belong to the repo instead of a specific crate.

Disadvantages
- Right now the docs config uses `"-Zrustdoc-scrape-examples=examples"` which I don't think will work by default in this new setup. I'm not sure if it's possible to make work in a setup like this, but it would make the docbuild process more complex I think

**Comment by arlyon** [comment]
I agree that splitting into crates would be nice. async-graphql is another example of examples done well imo, though not having the examples in the docs is a pretty major downside imo. It isn't clear to me if it is possible to parse this data from arbitrary crates though we _may_ be able to do some manipulation in build.rs to convert those crates into examples before the docs are generated...

I will leave this open for now but I think the inline examples are helpful in a) taming the surface area of the api in the docs and b) verifying our public interface. I realise b is still possible in both usecases however a is a little more complex.
