### ISSUE TITLE
Allow configuring minimum signature version without requiring an update

### ISSUE THREAD

**Issue by arlyon** [arlyon/async-stripe#292]
The purpose of the versioning in the signature is in the case of a signing key leak and them having to permanently invalidate v1 (as they have "done" for v0 for testing purposes). Perhaps it would make sense to rework this to allow configuring the minimum-supported signature version at runtime without requiring a new release of the library, that way in the event of a signature scheme, it is possible to simply migrate to the new one without a new release. 

At the same time, the signature time tolerance is currently hardcoded to 5 minutes; some more flexibility here would be nice.

_Originally posted by @arlyon in https://github.com/arlyon/async-stripe/pull/288#discussion_r1017784591_

**Comment by amab8901** [comment]
how do I reproduce the problem?

**Comment by arlyon** [comment]
Sorry @amab8901 I misunderstood how their schemes work in practice and I don't think we would benefit anything from making this runtime-configurable until they have a v2 (that is to say that a v2 _would_ probably require code changes). Closing this issue.
