### ISSUE TITLE
`SubscriptionPaymentBehavior` is inaccessible

### ISSUE THREAD

**Issue by ascclemens** [arlyon/async-stripe#301]
### Describe the bug

The `SubscriptionPaymentBehavior` enum is not accessible for `CreateSubscription::payment_behavior` ([docs](https://docs.rs/async-stripe/latest/stripe/struct.CreateSubscription.html#structfield.payment_behavior) also don't make it a link).

There is an enum with the same name (which is not compatible) in the generated `billing::subscription_item` module, as well.
![image](https://user-images.githubusercontent.com/955250/202023595-df4e118e-8698-40e3-b213-21866d1591ee.png)

### To Reproduce

```rs
    let mut create_subscription = CreateSubscription::new(customer_id);
    create_subscription.payment_behavior = Some(SubscriptionPaymentBehavior::DefaultIncomplete);
```

```
error[E0308]: mismatched types
   --> src/stripe/intent.rs:89:49
    |
89  |     create_subscription.payment_behavior = Some(SubscriptionPaymentBehavior::DefaultIncomplete);
    |                                            ---- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `stripe::resources::generated::billing::subscription::SubscriptionPaymentBehavior`, found enum `SubscriptionPaymentBehavior`
    |                                            |
    |                                            arguments to this enum variant are incorrect
    |
```

### Expected behavior

The enum should be accessible.

### OS

Fedora 36

### Rust version

rustc 1.66.0-nightly (2019147c5 2022-09-19)

### Library version

0.15

### API version

2022-08-01

**Comment by arlyon** [comment]
Hi! Thanks for using async-stripe. On master, #296 was recently landed that re-exports everything in the generated module so you can fall back to that in the case that duplicate classes cause the one you want to be swallowed.

Closing in favour of https://github.com/arlyon/async-stripe/issues/154 which has more context.
