### ISSUE TITLE
How to get CustomerId from String? and similar.

### ISSUE THREAD

**Issue by sloganking** [arlyon/async-stripe#328]
### Is your feature request related to a problem? Please describe.

I don't currently see a way to get a ``stripe::CustomerId`` from a `&str` or `String`, even though ``stripe::CustomerId`` has a `to_str()` function. 

### Describe the solution you'd like

allow `CustomerId::from(&str)` or `CustomerId::from(String)`.

### Describe alternatives you've considered
I want to be able to store `CustomerIds` in a DB (as strings), and retrieve Customer instances later from that. So Ultimately I want to get a `Customer` from a string representing a `CustomerId`. This could be done my making `Customer::retrieve()` possibly take a `String` instead of a `CustomerId`. But that seems like skipping a step.

**Comment by sloganking** [comment]
Here is the best work around I've come up with so far. Though it's very inefficient.

```rust
/// Returns `Some(stripe::Customer)` if a customer exists for the given string that
/// represents a CustomerId. Returns `None` otherwise.
async fn get_customer_from_id_string(
    client: &stripe::Client,
    customer_id_string: &str,
) -> Option<stripe::Customer> {
    let list_customers = stripe::ListCustomers {
        created: None,
        email: None,
        ending_before: None,
        expand: &[],
        limit: None,
        starting_after: None,
        test_clock: None,
    };

    let customers = Customer::list(client, &list_customers).await.unwrap();

    let mut customer_output: Option<stripe::Customer> = None;
    for customer in customers.data {
        // println!("customer: {:#?}", customer);
        if customer.id.as_str() == customer_id_string {
            println!("found customer {}", customer.name.clone().unwrap());
            customer_output = Some(customer);
            break;
        }
    }
    customer_output
}
```

**Comment by mzeitlin11** [comment]
`CustomerId` should impl `FromStr` (https://docs.rs/async-stripe/0.15.0/stripe/struct.CustomerId.html#impl-FromStr) - does `CustomerId::parse` work for your use case?

**Comment by sloganking** [comment]
It does work for my use-case. Here is a demonstration of using it. I should probaly handle the different `StripeError` cases returned from `Customer::retrieve` But this shows your suggestion works. Thanks!

```rust
/// Returns `Some(stripe::Customer)` if a customer exists for the given string that
/// represents a CustomerId. Returns `None` otherwise.
async fn get_customer_from_id_string(
    client: &stripe::Client,
    customer_id_string: &str,
) -> Option<stripe::Customer> {
    let customer_id = match customer_id_string.parse::<stripe::CustomerId>() {
        Ok(x) => x,
        Err(_) => return None,
    };
    let customer_option = Customer::retrieve(client, &customer_id, &[]).await.ok();

    if let Some(customer) = &customer_option {
        if customer.deleted {
            println!("customer is deleted");
            return None;
        }
        println!("found customer {:#?}", customer);
    }

    customer_option
}
```

**Comment by mzeitlin11** [comment]
> It does work for my use-case. Here is a demonstration of using it. I should probaly handle the different `StripeError` cases returned from `Customer::retrieve` But this shows your suggestion works. Thanks!
> 
> ```rust
> /// Returns `Some(stripe::Customer)` if a customer exists for the given string that
> /// represents a CustomerId. Returns `None` otherwise.
> async fn get_customer_from_id_string(
>     client: &stripe::Client,
>     customer_id_string: &str,
> ) -> Option<stripe::Customer> {
>     let customer_id = match customer_id_string.parse::<stripe::CustomerId>() {
>         Ok(x) => x,
>         Err(_) => return None,
>     };
>     let customer_option = Customer::retrieve(client, &customer_id, &[]).await.ok();
> 
>     if let Some(customer) = &customer_option {
>         if customer.deleted {
>             println!("customer is deleted");
>             return None;
>         }
>         println!("found customer {:#?}", customer);
>     }
> 
>     customer_option
> }
> ```

Great! To be clear, all the `{}Id` types like `CustomerId` are just a thin wrapper around `String` that ensures the prefix for the id is correct (`cus_` in the case of `CustomerId`). There is no validation that `CustomerId` actually corresponds to a `Customer` - just that the `Id` is formed correctly. (So `cus_123` would parse without error). 

That's why there's no handling of error cases like `Customer::retrieve` - you'd have to include that logic like you do above to ensure the invariant that `CustomerId` matches a `Customer`.

**Comment by sloganking** [comment]
For future readers. After looking around some more, it appears you can also use `CustomerId::from_str(customer_id_string)`, but you have to import `use std::str::FromStr;` first.

**Comment by arlyon** [comment]
`parse` actually uses `from_str` under the hood. I personally like the format:

```rust
let cid: CustomerId = "cus_123".parse()?;
```

**Comment by jblachly** [comment]
> For future readers. After looking around some more, it appears you can also use `CustomerId::from_str(customer_id_string)`, but you have to import `use std::str::FromStr;` first.

This was what I was missing in order to construct an otherwise-unconstructable `CheckoutSessionId`
