### ISSUE TITLE
Docs are not building on docs.rs

### ISSUE THREAD

**Issue by valkum** [arlyon/async-stripe#333]
### Describe the bug

Due to https://github.com/rust-lang/cargo/pull/10343, the cargo args for docs.rs need to be removed. 
Also rustdoc-scrape-examples is now enabled by default on docs.rs: https://github.com/rust-lang/docs.rs/pull/1954

### To Reproduce

Look at https://docs.rs/crate/async-stripe/0.15.1

### Expected behavior

Successful build

### OS

n/a

### Rust version

n/a

### Library version

0.15.1

### API version

n/a

**Comment by arlyon** [comment]
Thanks for raising this. I'll get it sorted!
