### ISSUE TITLE
Allow passing of parameters with stripe::Invoice::pay()

### ISSUE THREAD

**Issue by GrahameGW** [arlyon/async-stripe#352]
### Is your feature request related to a problem? Please describe.

I'm trying to mark an invoice paid by POSTing to the `invoice/{}/pay` endpoint with `paid_out_of_band=true`. Unfortunately, the `stripe::Invoice::pay()` method only accepts the `stripe::Client` and the `invoice.id` and does not allow for passing of the optional parameters as described by the endpoint (<https://stripe.com/docs/api/invoices/pay>)--or if it does the docs are not clear on how to achieve this. This seems like it might be similar to #218 and other issues here--if so I will work on using the `Client::post_form()` method to achieve the same goal until resolved.

If this task is possible via these functions, then some help understanding the docs on this point would be much appreciated.

Thanks!

### Describe the solution you'd like

Ideally, we could pass an `Option<PayInvoiceParameters>` or other similar struct to the `stripe::Invoice::pay()` function that would allow us to set these optional parameters when making our requests to the `invoice/{}/pay` endpoint.

### Describe alternatives you've considered

I am currently attempting to make the `stripe::Client::post_form()` method work for this goal; however I've been running into issues deserializing my querystring. It is entirely likely that I am simply botching the query string format here; the code I am using is as follows:
```
async fn mark_invoice_paid(
    invoice: stripe::Invoice,
    client: &stripe::Client,
) -> Result<stripe::Invoice, stripe::StripeError> {
    client
        .post_form::<stripe::Invoice, &str>(
            &format!("/invoices/{}/pay", invoice.id),
            "paid_out_of_band=true",
        )
        .await
}
```
which throws the following error:
```error serializing or deserializing a querystring: .: tried to serialize a value before serializing key```

presumably as part of the serialization step during the `Client::post_form()` method:
```        if let Err(qs_ser_err) = serde_path_to_error::serialize(&form, qs_ser) {
            return err(StripeError::QueryStringSerialize(qs_ser_err));
        }
```

**Comment by GrahameGW** [comment]
I got this to work by creating an `InvoiceParams` struct and going directly to the `Client::post_form()` method. After having slept on it a bit and re-reading the threads I'm pretty convinced this is part of the outstanding params issue in #218; I'll leave this ticket open in case it's not.

The fix if it's not is pretty simple--we can simply add an extension to the existing Invoice struct to have `pay()` use `post_form()` instead of `post()` (which it currently does) and allow for passing of a parameter struct--similar to how it's handled in other places (e.g., the `Charge` struct)

**Comment by arlyon** [comment]
Hi! I think adding an _ext is fine here until we finish overhauling the codegen. Open to PRs! Thanks for taking the time to investigate :)
