### ISSUE TITLE
SetupIntent::confirm() implementation does not exist

### ISSUE THREAD

**Issue by Ryanmtate** [arlyon/async-stripe#36]
While attempting to confirm a SetupIntent to attach a payment method to a customer, it appears the `SetupIntent::confirm()` method does not exist.

https://docs.rs/async-stripe/0.13.0-rc2/stripe/struct.SetupIntent.html#implementations

See stripe documentation: https://stripe.com/docs/api/setup_intents/confirm

**Comment by Ryanmtate** [comment]
It also appears that `PaymentIntent::confirm()` has an invalid variant for deserialization:

```
error reported by stripe: unknown_error(400): failed to deserialize error: unknown variant `payment_intent_unexpected_state`, expected one of `account_already_exists`, `account_country_invalid_address`, `account_invalid`, `account_number_invalid`, `alipay_upgrade_required`, `amount_too_large`, `amount_too_small`, `api_key_expired`, `balance_insufficient`, `bank_account_exists`, `bank_account_unusable`, `bank_account_unverified`, `bitcoin_upgrade_required`, `card_declined`, `charge_already_captured`, `charge_already_refunded`, `charge_disputed`, `charge_expired_for_capture`, `country_unsupported`, `coupon_expired`, `customer_max_subscriptions`, `email_invalid`, `expired_card`, `incorrect_address`, `incorrect_cvc`, `incorrect_number`, `incorrect_zip`, `instant_payouts_unsupported`, `invalid_card_type`, `invalid_charge_amount`, `invalid_cvc`, `invalid_expiry_month`, `invalid_expiry_year`, `invalid_number`, `invalid_source_usage`, `invoice_no_customer_line_items`, `invoice_no_subscription_line_items`, `invoice_not_editable`, `invoice_upcoming_none`, `livemode_mismatch`, `missing`, `order_creation_failed`, `order_required_settings`, `order_status_invalid`, `order_upstream_timeout`, `out_of_inventory`, `parameter_invalid_empty`, `parameter_invalid_integer`, `parameter_invalid_string_blank`, `parameter_invalid_string_empty`, `parameter_missing`, `parameter_unknown`, `payment_method_unactivated`, `payouts_not_allowed`, `platform_api_key_expired`, `postal_code_invalid`, `processing_error`, `product_inactive`, `rate_limit`, `resource_already_exists`, `resource_missing`, `routing_number_invalid`, `secret_key_required`, `sepa_unsupported_account`, `shipping_calculation_failed`, `sku_inactive`, `state_unsupported`, `tax_id_invalid`, `taxes_calculation_failed`, `testmode_charges_only`, `tls_version_unsupported`, `token_already_used`, `token_in_use`, `transfers_not_allowed`, `upstream_order_creation_failed`, `url_invalid` at line 3 column 45
```

It would be great to provide an example for `SetupIntent` or `PaymentIntent` that shows how a payment method can be attached to a customer and saved for an `off_session` usage checkout flow.

//

It seems creating a `PaymentIntent` "works", but it fails to attach the payment method to the customer when using the `setup_future_usage` option. I later receive an error when trying to setup a subscription.

```rust
let mut payment_intent_params = CreatePaymentIntent::new(50, Currency::USD);
payment_intent_params.customer = CustomerId::from_str(&stripe_customer_id).ok();
payment_intent_params.payment_method =
    PaymentMethodId::from_str(&stripe_payment_method_id).ok();
payment_intent_params.payment_method_types = Some(vec![String::from("card")]);
payment_intent_params.receipt_email = Some(&billing_email);
payment_intent_params.confirm = Some(true);
payment_intent_params.setup_future_usage =
    Some(PaymentIntentSetupFutureUsage::OffSession);

let intent = PaymentIntent::create(&self.client, payment_intent_params)
    .await
    .map_err(|e| Error::StripeError(e.to_string()))?;

info!("Created Payment Intent: {:?}", intent);
```

**Comment by arlyon** [comment]
Its not a secret that the test coverage for this needs some love. Ive been investing in observability in general, first getting the API generated automatically by a bot, then reworking the way the generated code is included to better see what is and isnt exposed.

The next stage is to start looking at coverage and tests, ideally each supported API would have at least one 'it works' test, there's no use shipping broken code.

Before that however, I'm going to convert all the tests to use one runtime so that we don't have to worry about which tests are designed for which runtime.

**Comment by Ryanmtate** [comment]
I hear you. I've tried generating a rust client from Stripe's openapi spec using openapi-generator-cli, and it fails with numerous errors.

Definitely a labor of love. Maybe I can help in some capacity to get this library more stable. I've also requested that stripe support an official rust client-- at the very least they could sponsor this project.

**Comment by arlyon** [comment]
I'm definitely open to PRs, or any other help you can provide, I have the time to keep quite on top of the repo for the forseeable future so I'd like to get this to the stage where it is considered 1.0 worthy. The contributing docs should explain the general layout, so if you'd like to add the impl for the intent `ext` files (or anything else) I'm happy to help out where needed.

I have also set up CI for all combinations of features so if you do write any tests, please use the async api, and put them behind `#[cfg(feature = "async")]`.

**Comment by Ryanmtate** [comment]
Thanks @arlyon I'll submit some PRs as I work through the use of the client.

I was able to successfully get the SetupIntent flow to attach a default payment method to a customer. The key was adding the payment method to the customer when the customer is initially created, along with setting up the invoicing settings with the default payment method.

While the confirm method does not exist, it appears that it may be unnecessary if you set `CreateSetupIntent.confirm = true`.

Will continue forward in testing the subscriptions flow, but attaching the default payment method is a great first step.

This did not require changes to the codebase.

Thanks again for your work on this. I am going to close this issue as it appears it may not be a blocker for others. If anyone runs into this in the future, feel free to reply here and I will share my setup in the event others may find it helpful.
