### ISSUE TITLE
Promo code creation?

### ISSUE THREAD

**Issue by affanshahid** [arlyon/async-stripe#389]
### Is your feature request related to a problem? Please describe.

I can't seem to find the documentation for creating a promo code like here: https://stripe.com/docs/api/promotion_codes/create

### Describe the solution you'd like

A function to generate a new promo code that wraps this endpoint: https://stripe.com/docs/api/promotion_codes/create

### Describe alternatives you've considered

I'm currently calling the endpoint directly

**Comment by arlyon** [comment]
Hey sorry for the delay, I have been on holiday :surfer: 

There is in fact not currently an API for creating promo codes, only listing, deleting, and updating. I would recommend following the pattern of the other extension objects and authoring this function in promo_code_ext.rs and opening a PR.

I will make sure to get it merged an released in a timely manner.

Cheers, Alex
