### ISSUE TITLE
Prorate Subscription

### ISSUE THREAD

**Issue by sloganking** [arlyon/async-stripe#394]
### Is your feature request related to a problem? Please describe.

https://stripe.com/docs/api/subscriptions/cancel

the stripe docs seem to allow prorating a subscription when you cancel it. However this libraries subscription cancellation function
https://docs.rs/async-stripe/0.22.2/stripe/generated/billing/subscription/struct.Subscription.html#method.cancel
Does not seem to allow prorating a subscription as it is canceled.

### Describe the solution you'd like

Allow prorating subscriptions in the [subscription cancel](https://docs.rs/async-stripe/0.22.2/stripe/generated/billing/subscription/struct.Subscription.html#method.cancel) function.

**Comment by sloganking** [comment]
I am not sure if this library currently offers a different way to prorate subscriptions, or just a way to view if they are prorated. As 
https://docs.rs/async-stripe/0.22.2/stripe/struct.RetrieveUpcomingInvoice.html#structfield.subscription_prorate
does exist.

**Comment by arlyon** [comment]
Closed in #411
