### ISSUE TITLE
Doesn't build on wasm32-unknown-unknown because of stdweb

### ISSUE THREAD

**Issue by rdbisme** [arlyon/async-stripe#432]
### Describe the bug

Hello, 
I'm trying to use this on Cloudflare Workers, but the build doesn't go throught because of: https://github.com/rustwasm/wasm-bindgen/issues/3415. 

Is there a way you might fix it? I think the `stdweb` dep is coming from `stdweb` -> `time` -> `cookie` -> `http_types`. 

### To Reproduce

Add 
```
async-stripe = { version = "*", default-features = false, features = [
    "runtime-async-std-surf",
    "webhook-endpoints",
] }
```
in cargo and `cargo build --target wasm32-unknown-unkown`. 

### Expected behavior

I'd love to use this crate with a WASM target

### OS

Linux (WSL)

### Rust version

1.70

### Library version

0.22.2

### API version

2023-08-16

**Comment by arlyon** [comment]
Hi! I have built this crate for wasm in the past (but before May 9) so I can confirm it works. I am not sure where your compile error comes from though, I don't see stdweb anywhere in the dep graph for this crate. If you can give me the exact `cargo tree` command I can use to repro, I can investigate.
