### ISSUE TITLE
Consider cutting release for 0.23

### ISSUE THREAD

**Issue by adamchalmers** [arlyon/async-stripe#439]
### Is your feature request related to a problem? Please describe.

I'd like to start using 0.23 so that I can get
 - updated hyper/rustls
 - fixes to the time crate and MSRV

### Describe the solution you'd like

Release the current master branch as 0.23

### Describe alternatives you've considered

I could use async-stripe as a Git dependency, it's just less convenient for me. But I can if you'd prefer not to cut the release yet.

**Comment by timsueberkrueb** [comment]
I second this request. @arlyon, any chance we can have a release? Thanks!

**Comment by arlyon** [comment]
Seems like some issue with the release script. I am manually publishing now.

**Comment by arlyon** [comment]
Yay! https://crates.io/crates/async-stripe

0.23.1 coming in a few minutes with the latest openapi changes also :)

**Comment by timsueberkrueb** [comment]
Thank you very much @arlyon!

**Comment by adamchalmers** [comment]
Thank you!
