### ISSUE TITLE
How to Finalize an Invoice?

### ISSUE THREAD

**Issue by oco-adam** [arlyon/async-stripe#442]
### Is your feature request related to a problem? Please describe.

Thanks very much for the great library! However, I can't figure out how to finalize an invoice, as in https://stripe.com/docs/api/invoices/finalize 

Apologies if this feature already exists, but I did search around the repo a fair bit before submitting this request.

### Describe the solution you'd like

To be able to finalise an invoice i.e. to move an invoice from draft status to open, as in https://stripe.com/docs/api/invoices/finalize

**Comment by arlyon** [comment]
Hi! You should be able to add this by putting the relevant api request in invoice_ext.rs. We are working on a revamp of the codegen that will make these manual extension apis obsolete but in the mean time non-crud things live in there. Shouldn't be too complicated if you'd like to submit a PR

**Comment by oco-adam** [comment]
Great, thank you - I’ll give it a go 👍🏼

**Comment by oco-adam** [comment]
Hi @arlyon pull request for this is here: 
https://github.com/arlyon/async-stripe/pull/450
