### ISSUE TITLE
Broken link to documentation on payments.rs

### ISSUE THREAD

**Issue by AdamIsrael** [arlyon/async-stripe#467]
### Describe the bug

The [Documentation](https://docs.rs/async-stripe/0.28.0/stripe) link on [payments.rs](https://www.payments.rs/) links to version 0.28.0, which I think is the latest release but the [latest docs](https://docs.rs/async-stripe/latest/stripe/) on docs.rs is for 0.26.0.

I think the website is correct in linking to 0.28.0 but those docs haven't been uploaded to docs.rs yet.

### To Reproduce

1. Visit [payments.rs](https://www.payments.rs/)
2. Click on the Documentation link
3. Be redirected to a page that says "The requested version does not exist"

### Expected behavior

The Documentation link should redirect to the docs for the latest release.

### OS

n/a

### Rust version

n/a

### Library version

n/a

### API version

n/a

**Comment by arlyon** [comment]
Yeah looks like you're right. The deploy process on this crate keeps breaking :( I will sort it out TY
