### ISSUE TITLE
Support pagination for Search queries

### ISSUE THREAD

**Issue by sjmiller609** [arlyon/async-stripe#468]
### Is your feature request related to a problem? Please describe.

Paginate for queries to Stripe Search API(s)

### Describe the solution you'd like

impl Paginable for Search types

### Describe alternatives you've considered

- I'm doing it wrong / didn't find how to do it properly using this SDK
- Don't use search endpoint
- Do pagination in my code

### Additional context

- Stripe docs for one of the search endpoints https://stripe.com/docs/api/customers/search
- Search for Paginable in this repo https://github.com/search?q=repo%3Aarlyon%2Fasync-stripe%20Paginable&type=code

**Comment by sjmiller609** [comment]
I think I'm missing something because of this release note https://github.com/arlyon/async-stripe/blob/8032120ab17a576b45faf4d9f385e8090d7d0ee3/CHANGELOG.md?plain=1#L32

**Comment by sjmiller609** [comment]
👀 https://github.com/mzeitlin11/async-stripe/blob/codegen_revamp/examples/pagination/src/main.rs

**Comment by sjmiller609** [comment]
This is the code that does not work

```rust
    let stripe_secret_key = get_stripe_secret_key()?;
    let client = stripe::Client::new(stripe_secret_key);
    // https://stripe.com/docs/search#query-fields-for-customers
    let customer_search = CustomerSearchParams {
        query: format!("-invoice_settings.default_payment_method:null"),
        limit: Some(90),
        ..Default::default()
    };

    let customers = match Customer::search(&client, customer_search.clone()).await {
        Ok(first_batch) => {
            let mut customers = first_batch.data;
            let paginator = first_batch.paginate(customer_search);
            while let Some(next_batch) = paginator.next(&client).await {
                customers.extend(next_batch.data);
            }
            customers
        },
        Err(e) => {
            error!("Failed to search for customer in Stripe: {:?}", e);
            return Err(ControlPlaneError::NetworkError(
                "Failed to search for customer in Stripe".to_string(),
            ));
        }
    };
    info!("Found {} customers with a payment method", customers.len());
    Ok(customers)
```

I was comparing to this https://github.com/arlyon/async-stripe/blob/8032120ab17a576b45faf4d9f385e8090d7d0ee3/examples/customer.rs#L60

**Comment by sjmiller609** [comment]
I think the param for paginate is the wrong type maybe https://github.com/arlyon/async-stripe/blob/8032120ab17a576b45faf4d9f385e8090d7d0ee3/src/params.rs#L217

**Comment by sjmiller609** [comment]
👀 https://github.com/arlyon/async-stripe/pull/414/files

**Comment by arlyon** [comment]
I have used this API before when testing the PRs in question but it is clearly broken. I should be stricter with mandating examples of public-facing apis. I am currently mostly focusing on the codegen revamp but will try to prioritise this after that is cleared.
