### ISSUE TITLE
`PaymentIntentUpdateParams` missing `payment_method`

### ISSUE THREAD

**Issue by grantperry** [arlyon/async-stripe#47]
According to the api docs this field is optional, but my workflow needs it available for update.

I tried looking for issues similar to this but did not find anything. I assume there is something mission from the openapi codegen.

I am happy to do the fix if you can point me in the right direction.

Thanks,
Grant

**Comment by grantperry** [comment]
So turns out there is a different struct that I should be using. `UpdatePaymentIntent` which does contain `payment_method`. Ignore me.

**Comment by arlyon** [comment]
Yeah the observability on this library is not stellar, any ideas you have to make the discovery process easier are welcome! Thanks for using async-stripe :)

**Comment by grantperry** [comment]
@arlyon it seems in the latest docs.rs release "0.13.0-rc3", the search function does not work. It does work in rc2. On understanding how to make changes to the openapi generation, is there any documentation? Or can you give me a quick rundown?

**Comment by arlyon** [comment]
Hey, sorry, yes that would be nice. I'll take a look so it's sorted for the proper release which should be soon.
