### ISSUE TITLE
Can't retrieve customer if i haven't got `CustomerId` which only can be got from creating a customer

### ISSUE THREAD

**Issue by vincent-thomas** [arlyon/async-stripe#498]
### Describe the bug

When i try to retrieve a customer from `Customer::retrieve()` i need to input from the struct `Customerid`. Which has a private field, and no functions that create a `CustomerId`, so its impossible to retrieve a customer, without having to create it in the same code block

### To Reproduce

```rs
   let test = Customer::retrieve(&c.stripe, &CustomerId("test"), &[".."]); // Error: error[E0423]: cannot initialize a tuple struct which contains private fields
```

On some inspection, the macro definition looks like this

```rs
#[derive(Clone, Debug, Default, Eq, PartialEq, Hash)]
pub struct $struct_name(/* private field => can't initialize myself */ smol_str::SmolStr);
```

If making the field pub it would make it possible to get customers without creating them

### Expected behavior

To be able to create a `CustomerId`, for then to retrieve the `Customer`

### OS

Not relevant

### Rust version

1.77.0-nightly - but not relevant

### Library version

0.31.0

### API version

2023-10-16

**Comment by augustoccesar** [comment]
Hello! Maybe what you are looking for is [`from_str`](https://docs.rs/async-stripe/0.31.0/stripe/struct.CustomerId.html#method.from_str).

```rust
let customer_id = CustomerId::from_str("cus_00aa1b")?;
let customer = Customer::retrieve(&client, &customer_id, &[]).await?;
```

**Comment by vincent-thomas** [comment]
Thank you this did work. Maybe implement the trait From<&str> and From<String> to follow that convention too? I know this is codegen so i don't think i can implement it but i think this would be a good idea.

**Comment by vincent-thomas** [comment]
Correction `TryFrom<&str>` trait as .from_str() returns `Result`
