### ISSUE TITLE
Inconsistent latest version in different places

### ISSUE THREAD

**Issue by lgarron** [arlyon/async-stripe#521]
### Describe the bug

https://www.payments.rs/ has a big button labelled "Documentation".

![Screenshot 2024-03-19 at 17 44 14](https://github.com/arlyon/async-stripe/assets/248078/20928474-3ae2-44b6-87f1-e7494f0aa6e0)

It links to https://docs.rs/async-stripe/0.34.2/stripe , which says "The requested version does not exist"

![Screenshot 2024-03-19 at 17 44 31](https://github.com/arlyon/async-stripe/assets/248078/b1f706e3-c3ed-454c-9f28-068c62690335)

https://docs.rs/async-stripe/latest/stripe/ shows the latest version as `v0.34.1`

![Screenshot 2024-03-19 at 17 44 50](https://github.com/arlyon/async-stripe/assets/248078/e7b4061e-016d-449d-899f-b903e1b90136)

The latest release shown on the GitHub project page is `v0.18.3`, because that's the latest version marked at https://github.com/arlyon/async-stripe/releases

![Screenshot 2024-03-19 at 17 45 15](https://github.com/arlyon/async-stripe/assets/248078/72d2445b-0e4b-4ba1-9a78-7cab89467b8f)

Also, the top of https://www.payments.rs/ contains a link that implies that it links to the tag `v0.34.2`, but that link actually just goes to https://github.com/arlyon/async-stripe (which only displays `v0.18.3` as the latest GitHub release, as mentioned above).

![Screenshot 2024-03-19 at 17 46 32](https://github.com/arlyon/async-stripe/assets/248078/1293c189-2a4f-4f97-8827-a56e2b5659b1)

This… does not inspire confidence for someone looking at this library for the first time. I'd recommend:

- Getting the exact latest version in sync between the repo, `crates`, and the website.
- Either [publishing](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) *all* release tags as releases on GitHub, or un-publishing all old ones to avoid confusion. (I personally recommend something automated to publish tags as releases on GitHub, like [this](https://github.com/cubing/actions-workflows?tab=readme-ov-file#publish-github-release).)

### To Reproduce

See above.

### Expected behavior

See above.

### OS

N/A

### Rust version

N/A

### Library version

N/a

### API version

N/A

**Comment by arlyon** [comment]
The automated release pipeline has been borked for a while sadly so I have been having to publish releases to GitHub manually. The latest version on the website is the latest _tag_ but not all tags have a github release which is all a bit messy. We are going to have to rework a decent chunk of the CI / release pipeline for the next branch once it is ready for primetime so I have been putting off fixing it since it'll be soon obsolete.

Apologies for the confusion. Also on my list is updating the readme alongside this stuff.

**Comment by jwiesler** [comment]
Semantic release is fixed.
