### ISSUE TITLE
Dependency breaks CI

### ISSUE THREAD

**Issue by ferrohd** [arlyon/async-stripe#532]
### Describe the bug

The [MSRV in CI is pinned to `1.68.0`](https://github.com/arlyon/async-stripe/blob/7ef5d3748540d86a72da002e5786c7d6faf29196/.github/workflows/async-stripe.yml#L114) but the dependency `lalrpop` requires at least `1.70.0` to build, failing the `test` matrix and blocking new PR like #518  #527 #524.

### To Reproduce

Trigger the CI by pushing to master or open a new PR.

### Expected behavior

A not failing CI

### OS

linux

### Rust version

1.68.0

### Library version

latest

### API version

latest

### Solution 1
Bump the MSRV in CI to `1.70.0`. This doesn't break the _3-versions-behind-latest_ rule, being `stable` at `1.77.0`

### Solution 2
Pin the `lalrpop` dependency to `0.20.0` which is the latest with MSRV <= `1.68.0`

**Comment by arlyon** [comment]
Thanks for the report. Got a PR that I will sort out tonight
