### ISSUE TITLE
doc.rs formatting is badly broken 

### ISSUE THREAD

**Issue by cowlicks** [arlyon/async-stripe#569]
### Describe the bug

Where the structs are displayed on the main [docs.rs page](https://docs.rs/async-stripe/0.37.1/stripe/index.html) the description of the struct is shown as a single column of text. Tested in chrome and safari. Looking at old versions this starts on 27.0. But it looks like the number of columns of text has been getting smaller and smaller before that.

<img width="1512" alt="Screenshot 2024-07-08 at 9 59 37 AM" src="https://github.com/arlyon/async-stripe/assets/598099/6aef0375-8ce1-425f-9b28-e9c5605e7b4e">

### To Reproduce

go to https://docs.rs/async-stripe/0.37.1/stripe/index.html

### Expected behavior

text is readable

### OS

macos

### Rust version

n/a

### Library version

37

### API version

none

**Comment by mzeitlin11** [comment]
Linking https://github.com/arlyon/async-stripe/issues/488 and https://github.com/rust-lang/rust/issues/120595, long type names are tricky :)

**Comment by arlyon** [comment]
Hey, @cowlicks, looks like this is fixed upstream so I expect the changes to bubble through to rustdoc shortly. I am closing this now!

**Comment by cowlicks** [comment]
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/8673ab02-f59d-4557-bbe6-ec81b0499509">
It's not perfect, but I'll take it. Thank you!
