### ISSUE TITLE
(next) Enums not being properly serialized

### ISSUE THREAD

**Issue by lasantosr** [arlyon/async-stripe#604]
### Describe the bug

On the stable branch we have enums like `UpTo` manually defined on the types crate, but that's not the case for _next_ branch, and some autogenerated enums ends up serializing incorrectly.

### To Reproduce

Try to create a price with `up_to: CreatePriceTiersUpTo::Inf` on any tier.

### Expected behavior

The price should be created, but instead it fails with an error:
```log
You passed an empty string for 'tiers[0][up_to]'. We assume empty values are an attempt to unset a parameter; however 'tiers[0][up_to]' cannot be unset. You should remove 'tiers[0][up_to]' from your request or supply a non-empty value.
```

### OS

all

### Rust version

1.74.0

### Library version

next

### API version

2024-04-10

### Additional context

Taking as an example [this](https://github.com/arlyon/async-stripe/blob/next/generated/async-stripe-product/src/price/requests.rs#L891) enum:
```rs
#[derive(Copy, Clone, Debug, serde::Serialize)]
#[serde(untagged)]
pub enum CreatePriceTiersUpTo {
    Inf,
    I64(i64),
}
```
`Inf` variant is incorrectly serialized to `null`, instead of `"inf"`, as explained [here](https://github.com/serde-rs/serde/issues/1560).

The correct enum would be:
```rs
#[derive(Copy, Clone, Debug, serde::Serialize)]
#[serde(rename_all = "snake_case")]
pub enum CreatePriceTiersUpTo {
    Inf,
    #[serde(untagged)]
    I64(i64),
}
```

**Comment by mzeitlin11** [comment]
Closing as fixed by #605, not sure why didn't happen automatically
