### ISSUE TITLE
Can't retrieve CheckoutSession using checkout_session_id query param

### ISSUE THREAD

**Issue by sytzez** [arlyon/async-stripe#608]
### Describe the bug

Sorry if there's already a solution to this problem, I haven't been able to find it, but I'm also quite new to using this crate.

In the [Stripe documentation](https://docs.stripe.com/payments/checkout/custom-success-page?locale=en-GB), it states that I should be able to retrieve the CheckoutSession when Stripe redirects the user to a page on my server using a session id query param in the URL.

I have tried using `CheckoutSession::retrieve` using an id of type `String`, extracted from the URL query. (I'm using `axum` by the way, but this should work similarly for any web server crate). However, I'm not able to construct a `CheckoutSessionId` from this `String`, and I've not found much documentation around these various `...Id` types which exist in `async-stripe`.

For the time being, I've made a workaround to this problem by copy-pasting and slightly modifying the code from `CheckoutSession::retrieve`, but I believe there should be a better way.

My workaround:

```rust
    let response: stripe::Response<stripe::CheckoutSession> = STRIPE_CLIENT.get_query(
        &format!("/checkout/sessions/{my_checkout_session_id_str}"),
        HashMap::<String, String>::new(),
    );
```

### To Reproduce

1. Get the checkout_session_id from a Stripe redirected URL generated using {{CHECKOUT_SESSION_ID}}
2. Try to retrieve the CheckoutSession using the checkout_session_id query param, which at this point is a String extracted by *insert Rust web server crate*

### Expected behavior

I would expect there to be a way to create a CheckoutSessionId from a String or &str.

### OS

Ubuntu

### Rust version

1.80.1

### Library version

async-stripe 0.39.1

### API version

2024-06-20

**Comment by augustoccesar** [comment]
Hello! Do you mean something like this?
```rust
let checkout_session_id = CheckoutSessionId::from_str("cs_test_xxxxxxx")?;
let checkout = CheckoutSession::retrieve(&client, &checkout_session_id, &[]);
```

**Comment by sytzez** [comment]
That's exactly what I was looking for, thanks!

**Comment by sytzez** [comment]
That's exactly what I was looking for, thanks!

**Comment by drauschenbach** [comment]
How is this done in the `next` branch?

**Comment by augustoccesar** [comment]
> How is this done in the `next` branch?

The ids on `next` also implement FromStr, so I guess the same way?

https://github.com/arlyon/async-stripe/blob/7042ec24f13d1fc45195c7b417e6610c9c616bd0/generated/async-stripe-checkout/src/checkout_session/types.rs#L967

https://github.com/arlyon/async-stripe/blob/7042ec24f13d1fc45195c7b417e6610c9c616bd0/async-stripe-types/src/ids.rs#L85-L91

It even has `From<String>` and `From<&str>`
https://github.com/arlyon/async-stripe/blob/7042ec24f13d1fc45195c7b417e6610c9c616bd0/async-stripe-types/src/ids.rs#L102-L114

So `CheckoutSessionId::from("cs_123")` should work as well.

```rust
let id1 = CheckoutSessionId::from("cs_123");
let id2 = CheckoutSessionId::from(String::from("cs_123"));
let id3 = CheckoutSessionId::from_str("cs_123");
```

**Comment by drauschenbach** [comment]
This line is what I cannot figure out how to do in the `next` branch:

```rust
let checkout = CheckoutSession::retrieve(&client, &checkout_session_id, &[]);
```

I was expecting to find some constructor of the pattern `CancelSubscription::new("cs_123").send(client)`, but I can't find anything.

**Comment by augustoccesar** [comment]
> This line is what I cannot figure out how to do in the `next` branch:
> 
> let checkout = CheckoutSession::retrieve(&client, &checkout_session_id, &[]);
> 
> I was expecting to find some constructor of the pattern `CancelSubscription::new("cs_123").send(client)`, but I can't find anything.

Your question is pointing to two different resources. Are you trying to retrieve a CheckoutSession or CancelSubscription?
Anyways, here is an example file on how to use the resources that might point you on the right direction: https://github.com/arlyon/async-stripe/blob/7042ec24f13d1fc45195c7b417e6610c9c616bd0/examples/endpoints/src/checkout.rs

But also, here is the retrieve checkout session request
https://github.com/arlyon/async-stripe/blob/7042ec24f13d1fc45195c7b417e6610c9c616bd0/generated/async-stripe-checkout/src/checkout_session/requests.rs#L181-L184

And here is the cancel subscription
https://github.com/arlyon/async-stripe/blob/7042ec24f13d1fc45195c7b417e6610c9c616bd0/generated/async-stripe-billing/src/subscription/requests.rs#L129-L132

**Comment by augustoccesar** [comment]
Good to note that on the `next` branch parts of the features are hidden behind feature flags, so that might be why you can't see them (not quite sure you meant by `but I can't find anything`)
As you can see here:
https://github.com/arlyon/async-stripe/blob/5ed7e1ef63402b5ff154e8b22dc96f4b0a8e00da/src/resources/generated.rs#L83-L116

So you need the feature `billing` enabled to be able to use Subscription features.

**Comment by augustoccesar** [comment]
That is odd 🤔  But also a bit out of the scope of this issue.
Can you open a new issue with your current setup, what you are trying to do so can be replicated and what issue/error you are getting?

**Comment by drauschenbach** [comment]
I figured this out. I was missing the `Retrieve` verb prefix to the command. Thanks!
